name: flutter_emoji
description: "ðŸ‘‰ A light-weight Emoji ðŸ“¦ for Flutter with all up-to-date emojis ðŸ˜„. Made from ðŸ’¯% â˜• with â¤ï¸!"
version: 3.0.0
homepage: "https://github.com/petehouston/flutter-emoji"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  characters: ^1.2.0
  http: ^0.13.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.20.1